import requests

BASE_URL = "http://localhost:5000"
TOKEN = "b6b347741b87b53be66d0263b691738515836a8128f26c58be50c9f86a4008a21dfce004959dfd99f97fc0e6a0956406822bd9f96aabf5343688ade678f940ed"
HEADERS = {
    "Authorization": f"Bearer {TOKEN}",
    "Content-Type": "application/json"
}
TIMEOUT = 30

def test_initiate_payment_for_completed_ride():
    ride_id = None
    booking_id = None
    ride2_id = None
    booking2_id = None
    try:
        # Step 1: Create a ride with 'completed' status
        ride_data = {
            "from": "Point A",
            "to": "Point B",
            "date": "2024-07-01T10:00:00Z",
            "seatsAvailable": 3,
            "pricePerSeat": 150,
            "status": "posted"
        }
        resp = requests.post(
            f"{BASE_URL}/api/rides",
            json=ride_data,
            headers=HEADERS,
            timeout=TIMEOUT
        )
        assert resp.status_code == 201, f"Ride creation failed: {resp.text}"
        ride = resp.json()
        ride_id = ride.get("_id")
        assert ride_id, "Ride ID missing in response"

        # Step 2: Update ride status to 'completed'
        status_update_resp = requests.put(
            f"{BASE_URL}/api/rides/{ride_id}/status",
            json={"status": "completed"},
            headers=HEADERS,
            timeout=TIMEOUT
        )
        assert status_update_resp.status_code == 200, f"Ride status update failed: {status_update_resp.text}"

        # Step 3: Book a seat on the completed ride
        booking_data = {
            "rideId": ride_id,
            "seatsBooked": 1
        }
        booking_resp = requests.post(
            f"{BASE_URL}/api/bookings",
            json=booking_data,
            headers=HEADERS,
            timeout=TIMEOUT
        )
        assert booking_resp.status_code == 201, f"Booking failed: {booking_resp.text}"
        booking = booking_resp.json()
        booking_id = booking.get("_id")
        assert booking_id, "Booking ID missing in response"

        # Step 4: Initiate Razorpay order for the booking/payment
        payment_order_resp = requests.post(
            f"{BASE_URL}/api/payments/razorpay/order",
            json={"bookingId": booking_id},
            headers=HEADERS,
            timeout=TIMEOUT
        )
        assert payment_order_resp.status_code == 200, f"Payment order creation failed: {payment_order_resp.text}"
        payment_order = payment_order_resp.json()
        assert "id" in payment_order and "amount" in payment_order, "Razorpay order response missing fields"
        assert payment_order["amount"] == 150 * 100, "Razorpay order amount mismatch"  # amount in paise

        # Step 5: Simulate payment verification with dummy signature data
        # Normally, signature and payment_id are generated by Razorpay payment flow - here we mock them
        verify_payload = {
            "razorpay_order_id": payment_order["id"],
            "razorpay_payment_id": "pay_dummy123456789",
            "razorpay_signature": "dummy_signature_for_testing"
        }
        verify_resp = requests.post(
            f"{BASE_URL}/api/payments/razorpay/verify",
            json=verify_payload,
            headers=HEADERS,
            timeout=TIMEOUT
        )
        # We expect failure because signature is dummy or success if API mocks verification for testing
        assert verify_resp.status_code in (200, 400), f"Unexpected status from payment verify: {verify_resp.status_code}"
        verify_result = verify_resp.json()
        if verify_resp.status_code == 200:
            assert verify_result.get("success") is True, "Payment signature verification failed unexpectedly"
            # Optionally, check that booking payment status updated:
            booking_status_resp = requests.get(
                f"{BASE_URL}/api/bookings/{booking_id}",
                headers=HEADERS,
                timeout=TIMEOUT
            )
            assert booking_status_resp.status_code == 200, f"Failed to get booking after payment verify: {booking_status_resp.text}"
            booking_after_payment = booking_status_resp.json()
            assert booking_after_payment.get("paymentStatus") == "paid", "Booking payment status not updated to paid"
        else:
            # If verification failed, check error message present
            assert "error" in verify_result, "Verify failed but no error message"

        # Step 6: Attempt to initiate payment for a non-completed ride and expect failure
        # Create another ride which is not completed (default: posted)
        ride2_resp = requests.post(
            f"{BASE_URL}/api/rides",
            json={
                "from": "Point C",
                "to": "Point D",
                "date": "2024-07-02T10:00:00Z",
                "seatsAvailable": 2,
                "pricePerSeat": 100
            },
            headers=HEADERS,
            timeout=TIMEOUT
        )
        assert ride2_resp.status_code == 201, f"Second ride creation failed: {ride2_resp.text}"
        ride2 = ride2_resp.json()
        ride2_id = ride2.get("_id")
        assert ride2_id, "Second ride ID missing"

        # Book seat on second ride
        booking2_resp = requests.post(
            f"{BASE_URL}/api/bookings",
            json={"rideId": ride2_id, "seatsBooked": 1},
            headers=HEADERS,
            timeout=TIMEOUT
        )
        assert booking2_resp.status_code == 201, f"Second booking failed: {booking2_resp.text}"
        booking2 = booking2_resp.json()
        booking2_id = booking2.get("_id")
        assert booking2_id, "Second booking ID missing"

        # Try to initiate payment order for second (not completed) ride's booking - should fail
        payment_order2_resp = requests.post(
            f"{BASE_URL}/api/payments/razorpay/order",
            json={"bookingId": booking2_id},
            headers=HEADERS,
            timeout=TIMEOUT
        )
        # Expecting error status code 400 or 403 for not allowed
        assert payment_order2_resp.status_code in (400, 403), "Payment initiation succeeded for non-completed ride, which is invalid"

    finally:
        # Cleanup: Delete created bookings and rides
        if booking_id:
            try:
                requests.delete(f"{BASE_URL}/api/bookings/{booking_id}", headers=HEADERS, timeout=TIMEOUT)
            except Exception:
                pass
        if booking2_id:
            try:
                requests.delete(f"{BASE_URL}/api/bookings/{booking2_id}", headers=HEADERS, timeout=TIMEOUT)
            except Exception:
                pass
        if ride_id:
            try:
                requests.delete(f"{BASE_URL}/api/rides/{ride_id}", headers=HEADERS, timeout=TIMEOUT)
            except Exception:
                pass
        if ride2_id:
            try:
                requests.delete(f"{BASE_URL}/api/rides/{ride2_id}", headers=HEADERS, timeout=TIMEOUT)
            except Exception:
                pass

test_initiate_payment_for_completed_ride()
